language: cpp
env: 
    - OMP_NUM_THREADS=4
    - C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include/libtcod
    - LD_LIBRARY_PATH=/usr/local/lib
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libboost1.54-tools-dev
    - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
    - sudo apt-get install -y libsdl2-dev libsdl-image1.2-dev
    - sudo apt-get install -y libpng++-dev
    - sudo apt-get install -y zlib1g-dev
    - sudo apt-get install -y libgl1-mesa-glx
    - sudo apt-get install -y libglew-dev
    - sudo apt-get install -y freeglut3-dev
    - sudo apt-get install -y libsdl2-dev
    - sudo apt-get install -y scons
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -y g++-5 gcc-5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 
before_script:
    - wget https://github.com/libtcod/libtcod/archive/1.9.0.zip -O libtcod-1.9.0.zip
    - unzip libtcod-1.9.0.zip
    - cd libtcod-1.9.0/build/scons
    - scons develop
compiler:
    - gcc
    - clang
script:
    - cmake .
    - make
